apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: armenia
  annotations:
    configsync.gke.io/cluster-name-selector: non-fleet-project-cluster-01,autopilot-cluster-1
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
