apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: armenia
  annotations:
    configmanagement.gke.io/cluster-selector: non-fleet-project-cluster-01
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
