kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: armenia
  name: namespace-reader
  annotations:
    configmanagement.gke.io/cluster-selector: fleet-cluster-0001,non-fleet-project-cluster-01
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
