kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: armenia
  name: namespace-reader
  annotations:
    configmanagement.gke.io/cluster-selector: selector-for-prod-env
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
