apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: ns-must-have-geo
  annotations:
    configmanagement.gke.io/cluster-selector: pc-dhl-demo-nfc
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    labels:
      - key: "org"
  excludedNamespaces:
      - config-management-system
      - gke-connect
      - kube-system
      - apigee