apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: AssignMetadata
metadata:
  name: set-labels-to-pod-deployment
spec:
  match:
    scope: "Namespaced"
    excludedNamespaces: ["dhl-1"]
  location: "metadata.labels.team"
  parameters:
    assign:
      value: "dhl"
