apiVersion: mutations.gatekeeper.sh/v1
kind: AssignMetadata
metadata:
  name: add-labels-team
spec:
  match:
    scope: Namespaced
  location: "metadata.labels.team"
  parameters:
    assign:
      value: "dhl"
      