apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: AssignMetadata
metadata:
  name: set-labels-to-pod-deployment
spec:
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pods", "Deployment"]
    namespaces: ["mutate"]
    scope: "Namespaced"
    excludedNamespaces: ["dhl-1"]
    labelSelector:
      matchLabels:
          app: "nginx"
      # matchExpressions:
      # - key: "team"
      #   operator: "Exists" # "In" or "NotIn" or "Exists" or "DoesNotExist"
  location: "metadata.labels.team"
  parameters:
    condition: "MustNotExist" 
    assign:
      value: "dhl"
