apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: AssignMetadata
metadata:
  name: set-labels-to-all
spec:
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pods", "Deployment"]
    namespaces: ["mutate"]
    scope: "Namespaced"
    excludedNamespaces: ["dhl-1"]
    labelSelector:
      matchExpressions:
      - key: "team"
        operator: "DoesNotExist" # "In" or "NotIn" or "Exists" or "DoesNotExist"
        values: ["dhl"]
  location: "metadata.labels.team"
  parameters:
    assign:
      value: "dhl"
